//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaire_Note
    {
        public int Id { get; set; }
        public string Commentaires { get; set; }
        public decimal Notes { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Users Users { get; set; }
    }
}
